<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/bootstrap.min.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/fontawesome.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/animate.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/cursor.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/slick.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/slick-theme.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/magnific-popup.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/vanilla-calendar.min.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/style.css" ?>">
<link rel="stylesheet" type="text/css" href="<?php echo URL . "assets/css/sweetalert.min.css" ?>">